#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <commit-hash>"
  exit 1
fi

hash=$1

echo "Running './gradlew detekt'..."
if ./gradlew detekt; then
    echo "Detekt passed ✅"

    git add -A

    git commit --fixup "$hash" -e

    git push
else
    echo "Detekt failed ❌"
    exit 1
fi
