#!/bin/bash

echo "Running './gradlew detekt'..."
if ./gradlew detekt; then
    echo "Detekt passed ✅"

    git add -A

    read -p "Enter ticket number: " ticket
    read -p "Enter commit message title: " message
    read -p "Enter commit description: " description

    git commit -m "GL-${ticket}: ${message}" -m "${description}"

    git push
else
    echo "Detekt failed ❌"
    exit 1
fi

