#!/bin/bash

echo "Running './gradlew detekt'..."
if ./gradlew detekt; then
    echo "Detekt passed ✅"

    git add -A
    
    branch=$(git rev-parse --abbrev-ref HEAD)
    revision="${branch#*/}"
    ticket="${revision%%/*}"

    read -p "Enter commit message title: " message
    read -p "Enter commit description: " description

    git commit -m "${ticket}: ${message}" -m "${description}"

    git push --set-upstream origin "${branch}"
else
    echo "Detekt failed ❌"
    exit 1
fi
